### ISSUE TITLE
Some UI elements in Applications view are very big now

### ISSUE THREAD

**Issue by Etamuk** [trifonovkv/ReminderAlarmClock#11]
Hello,

since the last update (yesterday or today) some elements in Gnome applications view are very big. Please see my screenshot. 
When I disable ReminderAlarmClock it looks fine again. 

I am using Pop OS 19.10 with GNOME 3.34.2

![Bildschirmfoto von 2020-03-26 15-27-02](https://user-images.githubusercontent.com/20098065/77658429-faa28380-6f76-11ea-94fb-31da1bfcc911.png)

**Comment by trifonovkv** [comment]
Hi, thanks for the report.
