### ISSUE TITLE
Timer is reset with lockscreen

### ISSUE THREAD

**Issue by Filbuntu** [trifonovkv/ReminderAlarmClock#12]
Thanks a lot for this handy extension!
When the lock screen kicks in and a password is needed to unlock it, the timer is reset.  Because of this I missed some appointments.
Could the Reminder-timer be kept during the lock screen?

**Comment by Filbuntu** [comment]
Wow, thanks a lot for this speedy fix! Much appreciated! I am looking forward to the update, hopefully the GNOME extension facilitator will pass it soon.

**Comment by trifonovkv** [comment]
You're welcome.  Let me know if there are any other bugs. 
Review the GNOME extensions last from a few of days to a few of weeks.

**Comment by Filbuntu** [comment]
Thanks again for the quick fix! It works as far as I can tell.
There is only a minor bug, the remaining time next to the indicator is reset to 00 after a lockscreen/blank screen even if there is still time till the alarm goes off. But I can live with this.
Thanks again!

**Comment by Filbuntu** [comment]
Thanks again the lightening quick fix! I am looking forward to testing it!
Have a great weekend!

**Comment by Filbuntu** [comment]
It works! Thank you very much!
