### ISSUE TITLE
Unable to set time

### ISSUE THREAD

**Issue by Strykar** [trifonovkv/ReminderAlarmClock#14]
I can use the presets to set a reminder 5, 10, 15 or 30 mins from the current time and it works.
I can't seem to edit the time, would be nice to be able to set a time for a repeatable reminder.

**Comment by trifonovkv** [comment]
Did I understand correctly that you want the option to set the time for a repeated reminder in the extension settings?
Can you describe in more detail what you mean?

**Comment by Strykar** [comment]
Yes, exactly.
