### ISSUE TITLE
Not installed in GNOME Shell 3.34.3

### ISSUE THREAD

**Issue by F50Ci37Y** [trifonovkv/ReminderAlarmClock#15]
Not installed in GNOME Shell 3.34.3 Ubuntu 19.10

**Comment by trifonovkv** [comment]
I can not reproduce this on Ubuntu 19.10 GNOME Shell 3.34.1

Try it:
- logout and login and start the installation again
- install this extension from a zip file

**Comment by F50Ci37Y** [comment]
Not working
![Screenshot from 2020-07-13 23-05-07](https://user-images.githubusercontent.com/20030910/87340456-53fde500-c55d-11ea-9c66-dfcac6a0b69b.png)

**Comment by trifonovkv** [comment]
```bash
cd ~/.local/share/gnome-shell/extensions/
rm -rf reminder_alarm_clock@trifonovkv.gmail.com/
wget https://github.com/trifonovkv/ReminderAlarmClock/releases/download/v9.0/reminder_alarm_clock@trifonovkv.gmail.com.zip
unzip reminder_alarm_clock@trifonovkv.gmail.com.zip -d reminder_alarm_clock@trifonovkv.gmail.com
rm reminder_alarm_clock@trifonovkv.gmail.com.zip
```

then restart the session

**Comment by F50Ci37Y** [comment]
> ```shell
> cd ~/.local/share/gnome-shell/extensions/
> rm -rf reminder_alarm_clock@trifonovkv.gmail.com/
> wget https://github.com/trifonovkv/ReminderAlarmClock/releases/download/v9.0/reminder_alarm_clock@trifonovkv.gmail.com.zip
> unzip reminder_alarm_clock@trifonovkv.gmail.com.zip -d reminder_alarm_clock@trifonovkv.gmail.com
> rm reminder_alarm_clock@trifonovkv.gmail.com.zip
> ```
> 
> then restart the session

![Screenshot from 2020-07-14 10-48-09](https://user-images.githubusercontent.com/20030910/87391206-8b9d7900-c5bf-11ea-9ef1-9036ce879173.png)

**Comment by trifonovkv** [comment]
Try [this](https://askubuntu.com/questions/142054/why-does-installing-gnome-shell-extensions-from-extensions-gnome-org-fail-silent) and [this](https://askubuntu.com/questions/56313/how-do-i-reset-gnome-to-the-defaults)

**Comment by dalisalvador** [comment]
Same. Also reset gnome to default. Not working

**Comment by trifonovkv** [comment]
Show the output of `journalctl -f -o cat /usr/bin/gnome-shell` when you get an error.
