### ISSUE TITLE
Gnome 40+

### ISSUE THREAD

**Issue by sojusnik** [trifonovkv/ReminderAlarmClock#18]
Would be great, if you could update it to work with Gnome 40+.

**Comment by smhg** [comment]
@trifonovkv I've tried the code in `master` on Gnome 40.4.0.
While it worked initially (right after installation with `gnome-extensions enable reminder_alarm_clock@trifonovkv.gmail.com`), after reboot it shows this error:

The settings of extension reminder_alarm_clock@trifonovkv.gmail.com had an error:
```
Error: No property margin on GtkGrid
```

Stack trace:
```
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
buildPrefsWidget@/home/username/.local/share/gnome-shell/extensions/reminder_alarm_clock@trifonovkv.gmail.com/prefs.js:32:23
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by nE0sIghT** [comment]
@smhg 
You are running v10, not master.  
There is no such code in master branch

**Comment by nE0sIghT** [comment]
I uploaded new version at e.g.o.: https://extensions.gnome.org/extension/2482/reminder-alarm-clock/
