### ISSUE TITLE
No reminder window nor notification is show on ubuntu 22.04

### ISSUE THREAD

**Issue by ManuelTS** [trifonovkv/ReminderAlarmClock#24]
Also not the test notification in the settings, my system:

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by nE0sIghT** [comment]
Please provide more details about your problem and the reopen this issue. Please attach gnome-shell logs and post screenshots etc
