### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by GerryT11** [trifonovkv/ReminderAlarmClock#28]
There are breaking changes which will require a separate extension release for Gnome 45 and <=44:

See Gnome 45 porting guide: https://gjs.guide/extensions/upgrading/gnome-shell-45.html

FYI, here is lots of information on the changes in Gnome 45 for extensions: https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/ . For early testing, they mention "You can test your extensions by downloading the latest [GNOME OS](https://os.gnome.org/) and trying your extension there."

**Comment by nE0sIghT** [comment]
Since I'm still on 43 now (44 broke Retroarch eg) this is `patch needed`
