### ISSUE TITLE
Don't use full minutes

### ISSUE THREAD

**Issue by sojusnik** [trifonovkv/ReminderAlarmClock#4]
If you set your timer to +1 minute when it is f.i. 15:49:45, then it will alarm at 15:50:00, thus only after 15 seconds and not after 1 minute, like you normally would expect. Therefore, I suggest changing that to the usual behaviour of timers – don't use full minutes, but rather the literal time. Following our example this would mean that the alarm should start at 15:50:45.

**Comment by trifonovkv** [comment]
Hey. I intentionally did this behaviour because I needed an alarm clock, not a timer.
The buttons set the time (hh: mm) when a message is displayed, rather than the timeout.
Do you think it's better to do as a timer?

**Comment by sojusnik** [comment]
I tend to use it as a timer stopping the exact time, f.i. when brewing tea I need 3 minutes, not 3½ etc. Would it be too complicated to add the "full minutes" feature to the settings and make the exact timing the default behaviour?

**Comment by trifonovkv** [comment]
Well, I will do this after I finish another project.
If you do not want to wait, you can simply in the file `~/.local/share/gnome-shell/extensions/reminder_alarm_clock@trifonovkv.gmail.com/extension.js` replace the line #37
```javascript
let distance = this.countDownDate.setSeconds(0) - new Date();
``` 
with the line
```javascript
let distance = this.countDownDate - new Date();
```
and reload the gnome-shell.
