### ISSUE TITLE
Behaviour when pressing "0"

### ISSUE THREAD

**Issue by sojusnik** [trifonovkv/ReminderAlarmClock#8]
Since the "0" is for resetting the timer, I would prefer not to see the pop-up message and hear the alarm (if configured), because I anyway know that I've resetted the timer by pressing "0". There's no need for the confirmation any more.

Additionally, the "0" could be renamed to "R" in order to clearly show that it stands for RESET.

**Comment by trifonovkv** [comment]
Button "0" not only to reset the time but also to check the notification settings. How then to check the notification settings? Add another button? I think it’s better to leave it as it is.

**Comment by sojusnik** [comment]
But how often do you check the notification settings? Maybe a couple of times while setting up everything. Therefore its place would be in the settings, as f.i. [this](https://extensions.gnome.org/extension/708/panel-osd/) extension does it. This button could be called "show test notification".

Afterwards "0" could be renamed to "R" and everything would be more intuitive, IMHO.
